# -*- coding: utf-8 -*-
"""RAMAYANA 1988 Episode List.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KMaKHmqD7Iak4FRXyGfuM7YQef-ev1SI
"""

import pandas as pd

dataset = pd.read_csv("/content/RAMAYANA.csv")

dataset.head(4)

dataset = dataset.drop("Unnamed: 0", axis = 1)

dataset["AIRED ON"][3]

import re
def remove_html_tags(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

dataset["AIRED ON"]= dataset["AIRED ON"].apply(remove_html_tags)

import re
def remove_html_tag(text):
    # Convert to string if the input is not a string
    if not isinstance(text, str):
        text = str(text)

    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

dataset["SUMMARY"]= dataset["SUMMARY"].apply(remove_html_tag)

dataset["SUMMARY"]

pd.set_option('display.max_rows', None)
dataset["SUMMARY"]

dataset

def split_and_keep_left(text):
    # Split the string at the "∙" symbol
    parts = text.split('∙')

    # Return the left part, which is the first element of the list
    return parts[0].strip() if parts else text

def split_and_keep_right(text):
    # Split the string at the "∙" symbol
    parts = text.split('∙')

    # Return the right part, which is the second element of the list
    return parts[1].strip() if len(parts) > 1 else text

dataset.head(3)

dataset["EPISODE"] = dataset["EPISODE"].apply(split_and_keep_left)
dataset["TITLE"] = dataset["TITLE"].apply(split_and_keep_right)

dataset.head(5)

pd.set_option('display.max_rows', None)
dataset

def extract_episode(text):
    # Use regex to find and return the "E" followed by numbers
    match = re.search(r'E\d+', text)
    return match.group() if match else None

dataset.head(3)

dataset["EPISODE"] = dataset["EPISODE"].apply(extract_episode)

dataset.head(4)

#Ramanand Sagar's Ramayan
dataset.to_csv("RAMAYAN: EPIC INDIAN TELEVISION SERIES.csv")

